"""
GenerateREADME — Auto-generates README files for the LSTM model.
=================================================================
Three READMEs are produced:
  - README_Training.md   → written at the end of training (LSTMTraining.py)
  - README_Evaluation.md → written after all evaluation plots are saved (Plotting.py)
  - README_Ensemble.md   → written after ensemble plots are saved (EnsembleOutput.py)

All are saved to the run's plot/output directory.
"""

import os
from datetime import datetime


# ============================================================
# Training README
# ============================================================

def generate_training_readme(plot_dir, model_filename, config,
                              train_size, val_size, cal_size, test_size, n_total,
                              epochs_run, best_epoch, best_val_loss,
                              conformal_u_alpha,
                              early_stopped, patience):
    """
    Write README_Training.md to plot_dir immediately after training completes.

    Args:
        plot_dir          : Directory where the README is saved.
        model_filename    : Filename of the saved checkpoint (e.g. model_v3.pth).
        config            : The Config instance used for training.
        train_size        : Number of training samples.
        val_size          : Number of validation samples.
        cal_size          : Number of conformal calibration samples.
        test_size         : Number of test samples.
        n_total           : Total dataset size.
        epochs_run        : Total number of epochs that were executed.
        best_epoch        : Epoch at which the best validation loss was recorded.
        best_val_loss     : Best validation loss.
        conformal_u_alpha : Scalar interval expansion from conformal calibration.
        early_stopped     : True if training was stopped early by the patience mechanism.
        patience          : The early-stopping patience value that was configured.
    """
    train_pct = train_size / n_total * 100
    val_pct   = val_size   / n_total * 100
    cal_pct   = cal_size   / n_total * 100
    test_pct  = test_size  / n_total * 100
    stop_note = (f"Yes — no improvement for {patience} consecutive epochs "
                 f"(stopped at epoch {epochs_run})") if early_stopped else "No — ran to completion"
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Collect all scalar config attributes
    config_rows = ""
    for key in sorted(dir(config)):
        if key.startswith("_"):
            continue
        value = getattr(config, key)
        if callable(value):
            continue
        config_rows += f"| `{key}` | {value} |\n"

    content = f"""\
# LSTM Training Run — Summary

Auto-generated by `LSTMTraining.py` on {generated_at}.

---

## Model

| Property | Value |
|---|---|
| Checkpoint file | `{model_filename}` |
| Best checkpoint epoch | {best_epoch} |
| Best validation loss | {best_val_loss:.6f} |
| Total epochs run | {epochs_run} |
| Early stopping triggered | {stop_note} |

---

## Conformal Calibration

| Property | Value |
|---|---|
| u_alpha (interval expansion) | {conformal_u_alpha:.4f} |
| Calibration set size | {cal_size} samples ({cal_pct:.1f}%) |
| Target coverage | 90% |

At inference time, apply to raw model outputs:

```
q10_calibrated = q10 - {conformal_u_alpha:.4f}
q90_calibrated = q90 + {conformal_u_alpha:.4f}
```

The calibration set is held out from training and model selection entirely,
so this coverage guarantee is valid on exchangeable future data.

---

## Dataset Split

| Split | Samples | Percentage | Role |
|---|---|---|---|
| Train | {train_size} | {train_pct:.1f}% | Model training |
| Validation | {val_size} | {val_pct:.1f}% | Early stopping / model selection |
| Calibration | {cal_size} | {cal_pct:.1f}% | Conformal calibration |
| Test | {test_size} | {test_pct:.1f}% | Final held-out evaluation |
| **Total** | **{n_total}** | **100%** | |

The split is **chronological** — no data leakage. Each set is strictly later
in time than the one before it.

---

## Hyperparameters (Config)

| Parameter | Value |
|---|---|
{config_rows}\
---

## Loss Curve

![Train vs Validation Loss](Plots/train_val_loss.png)

### How to interpret it

| Pattern | Meaning |
|---|---|
| Both curves decrease together | Training is progressing correctly |
| Val loss plateaus while train loss keeps falling | Overfitting — consider more dropout or less capacity |
| Both curves are flat from the start | Learning rate too low, or gradient issue |
| Loss spikes during training | Gradient explosion — check grad clipping |
| Best epoch is very early | Early stopping may have fired too soon — consider raising patience |
| Best epoch is near the configured max | Model may still improve with more epochs |

---

## Notes

- Loss function: **Quantile Loss** — the model outputs q10, q50, q90 for each
  forecast step, weighted 0.25 / 0.50 / 0.25.
- Gradient clipping is applied at `max_norm = 0.5` per step to prevent
  exploding gradients in the 168-step sequence.
- The learning rate scheduler (`ReduceLROnPlateau`, factor=0.5, patience=patience/2)
  halves the learning rate whenever validation loss stops improving.
"""
    readme_path = os.path.join(plot_dir, "README_Training.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)


# ============================================================
# Evaluation README
# ============================================================

def generate_evaluation_readme(plot_dir, best_epoch, best_val_loss,
                                n_test_samples, train_size, val_size, test_size, n_total,
                                model_filename="unknown"):
    """
    Write README_Evaluation.md to plot_dir explaining every evaluation plot,
    every panel, and how to interpret patterns in them.
    """
    train_pct = train_size / n_total * 100
    val_pct   = val_size   / n_total * 100
    test_pct  = test_size  / n_total * 100

    content = f"""\
# LSTM Forecast — Evaluation Plots

Auto-generated by `Plotting.py`.

## Model & Dataset Summary

| Property | Value |
|---|---|
| Model file | `{model_filename}` |
| Best checkpoint epoch | {best_epoch} |
| Best validation loss (GaussianNLL) | {best_val_loss:.6f} |
| Total samples | {n_total} |
| Train split | {train_size} ({train_pct:.1f}%) |
| Validation split | {val_size} ({val_pct:.1f}%) |
| Test split | {test_size} ({test_pct:.1f}%) |
| Forecast horizon | 168 hours (7 days) |
| Encoder history | 168 hours (7 days) |

---

## Plots Overview

| File | Contents |
|---|---|
| `test_predictions.png` | Three representative 168-hour forecast windows |
| `actual_vs_predicted.png` | Actual vs predicted scatter at 1h, 24h, and 168h ahead |
| `residuals.png` | Residual diagnostics: error over time, quantile heatmap, variance ratio |
| `per_horizon_metrics.png` | Per-horizon MSE / RMSE / MAE / MAPE / R² vs persistence baseline |

---


## Example Forecast Windows

![Example Forecast Windows](test_predictions.png)

### What it shows
Three 168-hour forecast windows sampled evenly from the test set (early, middle, late).
Each panel shows the actual abvaerk (blue) and the model prediction (red) over the full
7-day horizon. The MAE and date range for that window are shown in the title.

### How to interpret

| Pattern | Meaning |
|---|---|
| Red line tracks blue closely | Model is working well for that period |
| Red line is flat / near-constant | Model is predicting the mean — under-trained or mean-regressing |
| Red line tracks the shape but is shifted up or down | Systematic bias for that period |
| Errors are larger in one window than another | Model performs differently across seasons or weather regimes |
| Red line overshoots peaks | Model is over-dispersed for that window |

The three windows are spaced across the full test set so you can compare performance
across different time periods (e.g. early autumn vs late winter).

---

## Actual vs Predicted at Three Horizons

![Actual vs Predicted](actual_vs_predicted.png)

### What it shows
Three scatter plots side by side, each showing actual abvaerk (x-axis) against the
model's predicted abvaerk (y-axis) for a specific forecast horizon step. Each point
represents one test window. The dashed diagonal is the identity line `y = x` (perfect
prediction). The R² score for that horizon is shown in the title.

| Panel | Horizon | Description |
|---|---|---|
| Left | h=0 (1h ahead) | Sharpest prediction — model has the most context |
| Middle | h=23 (24h ahead) | 1-day-ahead prediction |
| Right | h=167 (168h ahead) | 7-day-ahead prediction — hardest step |

A small random jitter is added to the x-axis to separate overlapping points and reveal
density structure that would otherwise be hidden.

### How to interpret

| Pattern | Meaning |
|---|---|
| Points clustered tightly on the diagonal | High accuracy at that horizon |
| Scatter grows from left to middle to right panel | Normal degradation — model gets less accurate further out |
| Points form a fan shape (wider at high actual values) | Heteroscedastic error — model struggles more at peak demand |
| Points systematically above the diagonal | Model over-predicts on average at that horizon |
| Points systematically below the diagonal | Model under-predicts on average at that horizon |
| Middle and right panels look similar to the left | Model is not degrading with horizon — strong weather forecast features or mean regression |
| Two distinct clusters of points | Possible bi-modal demand (e.g. heating season vs non-heating) |
| R² drops sharply from left to right | Expected — forecast accuracy degrades with horizon distance |
| R² stays similar across all three panels | Either genuinely good long-range skill, or mean regression (check variance ratio plot) |

---

## Residual Diagnostics

![Residual Diagnostics](residuals.png)

### Panel layout
```
┌──────────────────────────────────────┐
│  Panel A: MAE over time (full width) │
├──────────────────────┬───────────────┤
│  Panel B: Quantile   │  Panel C:     │
│  error heatmap       │  Variance     │
│                      │  ratio        │
└──────────────────────┴───────────────┘
```

### Panel A — Forecast Error Over Time
MAE for each test window plotted in chronological order (one point = one 168-hour forecast
starting at that date). A red rolling mean (168-sample window) is overlaid to show the
trend.

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Gradual upward trend over time | Model degrades on later data — possible distribution shift |
| Sharp spike at a specific date | Model failed on an unusual event (cold snap, heat wave, holiday) |
| Lower error in summer, higher in winter | Model handles low-demand periods well but struggles with heating season |
| Error decreases over time | Test set may start mid-season transition and stabilise |
| Flat, consistent error throughout | Model generalises well across all periods |

### Panel B — Absolute Error Distribution by Horizon (quantile heatmap)
A 2D heatmap where:
- **X-axis**: forecast horizon in hours (1 = 1h ahead, 168 = 7 days ahead)
- **Y-axis**: error percentile (p5 = best 5% of windows, p95 = worst 5%)
- **Colour**: absolute error in MWh (yellow = low, dark red = high)

Vertical white dashed lines mark day boundaries (1d, 2d, … 7d).

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Colour gets darker left to right | Error grows with horizon — normal degradation |
| Colour is uniform across the full x-axis | Error does not grow with horizon — either genuinely good (weather forecasts help) or mean-regression |
| Only the top rows (p90, p95) darken at long horizons | Tail errors grow faster than median |
| All rows darken uniformly | Error distribution shifts up uniformly with horizon |
| Dark colours near the top even at short horizons | Large worst-case errors even at 1–2h ahead — high-variance regime |

### Panel C — Predicted vs Actual Variance Ratio per Horizon
The ratio `Var(predicted) / Var(actual)` computed at each of the 168 forecast steps.
The dashed black line at 1.0 is the ideal. Blue shading = under-dispersed region;
red shading = over-dispersed region.

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Orange line stays near 1.0 across all horizons | Model maintains realistic spread at all forecast distances |
| Line drops below 1.0 after a few hours and keeps falling | Mean regression — model predicts near-average values at longer horizons |
| Line starts above 1.0 at horizon 1–5 | Decoder is over-dispersed initially — common in under-trained models |
| Line is flat below 1.0 for the entire range | Model systematically under-represents variation |
| Line oscillates around 1.0 | Variance tracking is noisy but unbiased on average |

---

## Per-Horizon Metrics vs Persistence Baseline

![Per-Horizon Metrics](per_horizon_metrics.png)

### What it shows
Five vertically stacked subplots sharing the same x-axis (forecast horizon 1–168h).
Each shows the LSTM metric (coloured line) and the **persistence baseline** (gray dashed
line). Vertical gray dashed lines mark day boundaries (1d–7d).

### Metrics explained

| Metric | Unit | Ideal direction | Formula |
|---|---|---|---|
| MSE | MWh² | Lower is better | mean((pred − actual)²) |
| RMSE | MWh | Lower is better | sqrt(MSE) |
| MAE | MWh | Lower is better | mean(\\|pred − actual\\|) |
| MAPE | % | Lower is better | mean(\\|pred − actual\\| / actual) × 100 |
| R² | dimensionless | Higher is better (max 1.0) | 1 - SS\\_res / SS\\_tot |

---

## General notes

- All metrics are computed on the **test set only** ({test_size} samples, {test_pct:.1f}%
  of the data — chronologically the most recent). The model never saw this data during training.
- The persistence baseline uses the **last observed abvaerk value** from the encoder
  window repeated for all 168 forecast steps.
"""
    readme_path = os.path.join(plot_dir, "README_Evaluation.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)

# ============================================================
# Ensemble README
# ============================================================

def generate_ensemble_readme(plot_dir, ensemble_size, model_filename="unknown", generated_plots=None):
    """
    Write README_Ensemble.md to plot_dir after all ensemble plots are saved.
    Active plots (in generated_plots) get an embedded image + full explanation.
    Disabled plots are listed briefly in an 'Optional plots' section.

    Args:
        plot_dir        : Directory where the README and plots are saved.
        ensemble_size   : Number of models in the ensemble.
        model_filename  : The base LSTM checkpoint the ensemble was built on.
        generated_plots : List of filenames actually saved this run.
    """
    if generated_plots is None:
        generated_plots = []

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    PLOT_DOCS = {
        f"week_forecast_ensemble_week2.png": (
            "Weekly Forecast with Uncertainty",
            f"""\
A single 168-hour (7-day) window from the test set. Three elements are plotted:
- **Actual abvaerk** (solid line) — the ground truth
- **Predicted mean** (solid line) — the ensemble average across all {ensemble_size} models
- **±2σ band** (shaded) — the total uncertainty interval covering ~95% of a Gaussian

| Pattern | Meaning |
|---|---|
| Actual stays inside the ±2σ band most of the time | Well-calibrated uncertainty |
| Actual frequently outside the band | Uncertainty is underestimated |
| Band is very wide throughout | Over-confident uncertainty estimate, or high inherent data noise |
| Band narrows at predictable hours and widens at transitions | Model is more certain at regular demand patterns |
| Band widens beyond 24h and keeps growing | Normal: uncertainty accumulates with forecast distance |
| Band stays the same width regardless of horizon | Model may be collapsing to mean predictions at long horizons |
| Mean tracks actual well but band is very wide | Aleatoric uncertainty dominates |
| Mean drifts away from actual and band does not cover it | Systematic bias — model is missing a feature or pattern |"""
        ),
        "calibration_curve.png": (
            "Calibration Curve",
            """\
The x-axis shows the **theoretical coverage** of a Gaussian interval (e.g. 68% for ±1σ,
95% for ±2σ). The y-axis shows the **empirical coverage** — the actual fraction of test
points that fell inside that interval. The dashed diagonal is the ideal: perfect
calibration. Each point corresponds to a different σ multiplier (0.5σ → 3.0σ).

| Pattern | Meaning |
|---|---|
| Curve follows the diagonal closely | Well-calibrated ✓ |
| Curve is above the diagonal | Conservative (over-dispersed) — intervals are too wide |
| Curve is below the diagonal | Overconfident (under-dispersed) — intervals are too narrow |
| Curve starts below diagonal then crosses above | Mixed calibration |
| Curve is flat / horizontal | Uncertainty estimates are not varying meaningfully |
| S-shaped curve | Bimodal error distribution |"""
        ),
        "residuals_ensemble.png": (
            "Residuals Over Time",
            """\
The difference (actual − predicted mean) plotted for every test timestep in
chronological order. A rolling mean is overlaid to expose seasonal trends.

| Pattern | Meaning |
|---|---|
| Residuals centred near zero throughout | No systematic bias |
| Persistent positive residuals | Model consistently under-predicts |
| Residuals spike at certain dates | Model failed on an unusual event |
| Residuals grow larger in winter | Model struggles with heating-season demand peaks |"""
        ),
        "uncertainty_histogram.png": (
            "Uncertainty Distribution",
            """\
Histogram of total predictive standard deviation (σ) across all test timesteps.

| Pattern | Meaning |
|---|---|
| Narrow, single-peaked histogram | Model has similar confidence everywhere |
| Wide or flat histogram | Uncertainty varies greatly — expected for seasonal demand |
| Bimodal histogram | Two distinct uncertainty regimes (e.g. summer vs winter) |
| Very low std values throughout | Model may be under-dispersed — check calibration curve |"""
        ),
        "prediction_vs_actual.png": (
            "Predicted vs Actual Scatter",
            """\
Scatter plot of predicted mean (y) vs actual abvaerk (x) for every test timestep.
The dashed diagonal is perfect prediction (y = x).

| Pattern | Meaning |
|---|---|
| Points tightly clustered on the diagonal | High accuracy across the full range |
| Fan shape (wider at high values) | Model struggles at peak demand |
| Points systematically above the diagonal | Model over-predicts on average |
| Points systematically below the diagonal | Model under-predicts on average |"""
        ),
        "uncertainty_vs_error.png": (
            "Uncertainty vs Absolute Error",
            """\
Scatter of predicted total σ (x) vs absolute error (y) for every test timestep.
A well-calibrated model should show a positive correlation.

| Pattern | Meaning |
|---|---|
| Clear positive correlation | Uncertainty estimates are informative and trustworthy ✓ |
| Flat cloud (no correlation) | Uncertainty estimates are uninformative |
| Negative correlation | Pathological — model is most uncertain where it is most accurate |"""
        ),
    }

    active   = [f for f in PLOT_DOCS if f in generated_plots]
    disabled = [f for f in PLOT_DOCS if f not in generated_plots]

    overview_rows = ""
    for fname in active:
        title, _ = PLOT_DOCS[fname]
        overview_rows += f"| `{fname}` | {title} |\n"

    active_sections = ""
    for fname in active:
        title, explanation = PLOT_DOCS[fname]
        active_sections += f"""\
---

## `{fname}` — {title}

![{title}]({fname})

{explanation}

"""

    if disabled:
        disabled_section = "---\n\n## Optional Plots (currently disabled)\n\n"
        disabled_section += (
            "Enable these in `EnsembleOutput.py` by uncommenting the relevant lines "
            "in `_GeneratePlots`.\n\n"
        )
        for fname in disabled:
            title, explanation = PLOT_DOCS[fname]
            disabled_section += f"### `{fname}` — {title}\n\n{explanation}\n\n"
    else:
        disabled_section = ""

    content = f"""\
# Ensemble LSTM — Uncertainty Quantification Plots

Auto-generated by `EnsembleOutput.py` on {generated_at}.

---

## What is the Ensemble?

Instead of training a single LSTM model, the ensemble trains **{ensemble_size} independent
models** with different random seeds. Each model sees the same data but starts from a
different random initialisation, producing slightly different predictions.

| Uncertainty type | Source | Meaning |
|---|---|---|
| **Epistemic** | Disagreement between the {ensemble_size} models | What the model *doesn't know* — reduces with more data/training |
| **Aleatoric** | Each model's own predicted variance (GaussianNLL output) | Inherent noise in the data — cannot be reduced |
| **Total** | Combined epistemic + aleatoric | The full predictive uncertainty |

Base model: `{model_filename}`

---

## Plots Overview

| File | Contents |
|---|---|
{overview_rows}
{active_sections}{disabled_section}---

## General Notes

- All plots use the **test set only** — the ensemble never saw this data during training.
- A larger ensemble reduces the variance of the epistemic uncertainty estimate but
  increases training time proportionally.
"""
    readme_path = os.path.join(plot_dir, "README_Ensemble.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)